// Selección editorial: 47 cuentas de Instagram y 25 webs latinoamericanas.
// Ninguna de estas entradas ha pagado por aparecer.
const instagramProfiles = [
  ['Antonieta Fashionway','antonietafashionway','Moda y estilo en Instagram.'],
  ['Melissa Sombrerero','melissa.sombrerero','Viajes y destinos en Instagram.'],
  ['Kara Alvarez','karykaryalvarez','Viajes y escapadas en Instagram.'],
  ['Erika Martínez','erikamtzga','Viajes y experiencias en Instagram.'],
  ['Denisse Fly','denissefly','Rutas y viajes en Instagram.'],
  ['Jocelyn Brieno','jocelyn_brieno','Viajes y recomendaciones en Instagram.'],
  ['Luisa Polo','luissapolo','Destinos y experiencias en Instagram.'],
  ['Berenice Anguiano','anguianoberenice','Viajes y lugares en Instagram.'],
  ['Nick Guillory','nickguillory','Viajes por México en Instagram.'],
  ['Ari Viajera','ariadnaglzc','Viajes y aventuras en Instagram.'],
  ['Champi Alvarez','champitravels','Rutas y viajes en Instagram.'],
  ['Camila Suárez','eltenedorosado','Gastronomía colombiana en Instagram.'],
  ['Pedro Fernández','thechefisback','Cocina y gastronomía en Instagram.'],
  ['Mariana Arango','marrana.eats','Restaurantes y comida en Instagram.'],
  ['José Iskandar','food.o.grafo','Fotografía gastronómica en Instagram.'],
  ['Haslly de la Peña','foodiefotografa','Comida y fotografía en Instagram.'],
  ['Melissa Marrero','alwayshungrymel','Restaurantes y lugares para comer en Instagram.'],
  ['Claudia Ledezma','foodhunterco','Lugares para comer en Instagram.'],
  ['Jenn Muñoz','alamesaconjenn','Comida y experiencias en Instagram.'],
  ['Manashin Ozaki','machan_colombia_1102','Gastronomía en Instagram.'],
  ['Justin','justinthetable','Cocina y restaurantes en Instagram.'],
  ['Juan Camilo','crumont','Recetas y gastronomía en Instagram.'],
  ['María Camila Cano','camcakes___','Restaurantes, viajes y planes en Instagram.'],
  ['Steph Barrientos','jamaenruta','Experiencias gastronómicas en Instagram.'],
  ['Magda Pérez','placeresculpososblog','Gastronomía peruana en Instagram.'],
  ['Adrián Alvarado','elcuerpodeolla','Cocina peruana en Instagram.'],
  ['Alonso Sánchez','alonso_food','Comida y restaurantes en Instagram.'],
  ['Giuls','giuliannasoriano','Comida y experiencias en Instagram.'],
  ['Lucciano Martínez','djfoodie.pe','Gastronomía en Instagram.'],
  ['Cata Farina','catafarinia','Moda y estilo en Instagram.'],
  ['Florencia Figola','florenciafigola','Moda e inspiración en Instagram.'],
  ['Tomás Grunwaldt','tomas.grunwaldt','Moda y estilo en Instagram.'],
  ['Victoria Esteche','vickyestt','Moda y tendencias en Instagram.'],
  ['Clara Trillo','claratrillo','Estilo personal en Instagram.'],
  ['Martín Remine','remartinn','Moda y contenido en Instagram.'],
  ['Luca Maffia','luca.maffiaa','Estilo y moda en Instagram.'],
  ['Tomás Nehuén','tomasnehuenl','Moda e inspiración en Instagram.'],
  ['Micaela Yela','micaelayela','Moda y estilo en Instagram.'],
  ['Arianna Gomez','_ariannagomez','Moda y tendencias en Instagram.'],
  ['Teff Kazelian','teffkazeliandiez','Moda e inspiración en Instagram.'],
  ['Tobias Cortella','tobiascortella','Estilo y contenido en Instagram.'],
  ['Bricia López','bricialopez','Cocina mexicana en Instagram.'],
  ['Maggie Unzueta','mamamaggieskitchen','Recetas mexicanas en Instagram.'],
  ['Yvette Márquez','muybuenocooking','Cocina mexicana en Instagram.'],
  ['Rossana Figueroa','villacocinaofficial','Recetas mexicanas en Instagram.'],
  ['Denise Favela','hechovistocomido','Gastronomía mexicana en Instagram.'],
  ['Silvia Martínez','mamalatina','Cocina y familia en Instagram.']
];
const latinWebsites = [
  ['Marketing','Vilma Núñez','Estrategias y formación de marketing digital.','https://vilmanunez.com/'],
  ['Marketing','Rock Content','Recursos de marketing de contenidos en español.','https://rockcontent.com/es/blog/'],
  ['Marketing','Doppler','Email marketing y automatización en español.','https://www.fromdoppler.com/es/'],
  ['Agentes','B2Chat','Atención y ventas por chat.','https://www.b2chat.io/'],
  ['Agentes','Aivo','Soluciones conversacionales para atención al cliente.','https://www.aivo.co/es/'],
  ['Agentes','Cliengo','Chatbots y gestión de conversaciones comerciales.','https://www.cliengo.com/'],
  ['Agentes','Yalo','Comercio conversacional impulsado por IA.','https://www.yalo.ai/'],
  ['Trading','CriptoNoticias','Noticias y educación sobre criptoactivos.','https://www.criptonoticias.com/'],
  ['Trading','Ripio','Servicios de criptoactivos para Latinoamérica.','https://www.ripio.com/'],
  ['Trading','Lemon','Aplicación de criptoactivos en español.','https://www.lemon.me/'],
  ['Desarrollo','Platzi','Cursos de tecnología y programación en español.','https://platzi.com/'],
  ['Otros','Mercado Libre','Comercio electrónico en Latinoamérica.','https://www.mercadolibre.com/'],
  ['Otros','Rappi','Pedidos y entregas a domicilio.','https://www.rappi.com/'],
  ['Otros','Tiendanube','Tiendas online para negocios de Latinoamérica.','https://www.tiendanube.com/'],
  ['Productividad','Alegra','Facturación y gestión para negocios.','https://www.alegra.com/'],
  ['Productividad','Siigo','Software contable y administrativo.','https://www.siigo.com/'],
  ['Otros','Wompi','Pagos digitales para comercios.','https://wompi.com/'],
  ['Otros','Kushki','Infraestructura de pagos latinoamericana.','https://www.kushkipagos.com/'],
  ['Otros','Clip','Soluciones de pago para negocios.','https://clip.mx/'],
  ['Otros','Conekta','Pagos online para comercios.','https://www.conekta.com/'],
  ['Otros','Kueski','Servicios financieros digitales.','https://www.kueski.com/'],
  ['Trading','Bitso','Plataforma de activos digitales.','https://bitso.com/'],
  ['Trading','Fintual','Inversiones y gestión de fondos.','https://fintual.com/'],
  ['Productividad','Buk','Software de gestión de personas.','https://www.buk.cl/'],
  ['Desarrollo','Crehana','Aprendizaje y desarrollo profesional.','https://www.crehana.com/']
];
const directoryEntries = [
  ...instagramProfiles.map(([name,handle,description],i)=>({category:'Social Media',name,description,url:`https://www.instagram.com/${handle}/`,...(i===0?{featured:true}:{})})),
  ...latinWebsites.map(([category,name,description,url])=>({category,name,description,url}))
];
