const categories=[['Todas','▦'],['Social Media','♡'],['Marketing','⚑'],['SEO','⌕'],['Trading','↗'],['Productividad','☷'],['Agentes','♙'],['Desarrollo','⌘'],['Rankings','♕'],['Otros','✧']];
const MIN_PRICE=0.50;
const palette=[['#222327','#f5f5f5'],['#e8e4ff','#5b48a8'],['#e9f4e9','#27634d'],['#fff0e3','#a95a3f'],['#e7f2ff','#3f68a5'],['#f3e9f6','#815298'],['#e6f7f5','#267a73'],['#fff3db','#91621e']];
const rankByIndex=new Map(directoryEntries.map((entry,i)=>({entry,i})).sort((a,b)=>(a.i%8)-(b.i%8)||Number(Boolean(b.entry.featured))-Number(Boolean(a.entry.featured))||a.i-b.i).map((item,rank)=>[item.i,rank]));
const bidForRank=rank=>(443-Math.round(rank*343/Math.max(1,directoryEntries.length-1)))/100;
const socialHandle=url=>new URL(url).pathname.split('/')[1]?.replace(/^@/,'');
const editorialAsset=entry=>{
  const url=new URL(entry.url),host=url.hostname.replace(/^www\./,'');
  return socialAssets[socialHandle(entry.url)]?.asset||brandAssets[host]?.asset||`https://www.google.com/s2/favicons?domain=${encodeURIComponent(host)}&sz=128`;
};
const projects=directoryEntries.map((entry,i)=>({
  ...entry,
  bid:bidForRank(rankByIndex.get(i)),
  todayBid:bidForRank(rankByIndex.get(i)),
  icon:entry.name.slice(0,1).toUpperCase(),
  logo:editorialAsset(entry),
  smallLogo:editorialAsset(entry),
  avatar:Boolean(socialAssets[socialHandle(entry.url)]),
  wideLogo:Boolean(brandAssets[new URL(entry.url).hostname.replace(/^www\./,'')]?.wide),
  bg:palette[i%palette.length][0],
  fg:palette[i%palette.length][1]
}));
let paidProjects=[],paymentsReady=false;const targetProjectId=new URLSearchParams(location.search).get('proyecto');let targetApplied=false;function validSavedBid(value){const bid=Number(value),cents=Math.round(bid*100);return Number.isSafeInteger(cents)&&Math.abs(bid*100-cents)<0.000001&&bid>=MIN_PRICE}
let category='Todas',period='all',page=1,query='',offer=4.44,automaticOffer=true;const pageSize=50;const $=id=>document.getElementById(id);const amountFormat=new Intl.NumberFormat('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2});const formattedAmount=n=>amountFormat.format(n);const money=n=>'$'+formattedAmount(n);
function readMoneyInput(input){const digits=input.value.replace(/\D/g,'');const cents=Number(digits);return Number.isSafeInteger(cents)?cents/100:null}
function writeMoneyInput(input,amount){input.value=formattedAmount(amount);if(input.id==='claim-price')input.style.width=Math.max(4.9,input.value.length+0.3)+'ch';else input.style.removeProperty('width')}
function normalizeMoneyInput(input){const amount=readMoneyInput(input);if(amount===null)return null;writeMoneyInput(input,amount);input.setSelectionRange(input.value.length,input.value.length);return amount}
const make=(tag,cls,value)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(value!==undefined)el.textContent=value;return el};
function applyLogo(icon,project,large=false){const source=large?project.logo:(project.smallLogo||project.logo);if(!source){icon.textContent='◎';return}const img=make('img');img.src=source;img.alt='';img.loading='lazy';img.onerror=()=>{img.remove();icon.textContent='◎';icon.classList.remove('has-logo')};icon.replaceChildren(img);icon.classList.add('has-logo');if(large&&project.wideLogo)icon.classList.add('wide-wordmark');if(project.avatar)icon.classList.add('social-avatar')}
const allProjects=()=>[...projects,...paidProjects];
const validUrl=value=>{try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}};
const normalizedUrl=value=>{const raw=String(value||'').trim();return validUrl(/^https?:\/\//i.test(raw)?raw:`https://${raw}`)};
const isSocialProfile=value=>{try{return /^(?:www\.)?(?:(?:instagram|tiktok|facebook|youtube|linkedin|pinterest|threads)\.com|x\.com|twitch\.tv)$/i.test(new URL(value).hostname)}catch{return false}};
function updateQuickUrlIcon(){const icon=$('quick-url-icon'),raw=$('quick-url').value.trim();let host='';try{const parsed=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`);if(/^(?:[a-z0-9-]+\.)+[a-z]{2,}$/i.test(parsed.hostname)&&raw.length>=parsed.hostname.length)host=parsed.hostname.toLowerCase()}catch{}if(!host){icon.textContent='◎';delete icon.dataset.host;return}if(icon.dataset.host===host)return;icon.dataset.host=host;const img=make('img');img.alt='';img.src=`https://www.google.com/s2/favicons?domain=${encodeURIComponent(host)}&sz=64`;img.onerror=()=>{if(icon.dataset.host===host)icon.textContent='◎'};icon.replaceChildren(img)}
$('quick-url').addEventListener('input',updateQuickUrlIcon);updateQuickUrlIcon();
function filtered(){return allProjects().filter(p=>(category==='Todas'||p.category===category)&&(period==='all'||p.todayBid>0)&&(`${p.name} ${p.description} ${p.category}`.toLowerCase().includes(query))).sort((a,b)=>(period==='today'?b.todayBid-a.todayBid:b.bid-a.bid)||Number(Boolean(b.featured))-Number(Boolean(a.featured)))}
function rankForBid(amount,cat=category,term=period){return 1+allProjects().filter(p=>(cat==='Todas'||p.category===cat)&&(term==='today'?p.todayBid:p.bid)>=amount).length}
function topOffer(cat=category,term=period){const bids=allProjects().filter(p=>cat==='Todas'||p.category===cat).map(p=>Math.round((term==='today'?p.todayBid:p.bid)*100));return (Math.max(49,...bids)+1)/100}
function updatePrice(syncInput=true){if(syncInput)writeMoneyInput($('claim-price'),offer);const rank=rankForBid(offer);$('claim-label').textContent=rank===1?'Consigue el Top':'Consigue el puesto';$('claim-rank').textContent=rank===1?'':` #${rank}`;$('price-down').disabled=offer<=MIN_PRICE;$('price-up').disabled=!validSavedBid(Number((offer+0.01).toFixed(2)));const occupied=allProjects().some(p=>p.bid===offer),hint=$('price-hint');hint.hidden=!occupied&&offer>=MIN_PRICE;hint.textContent=offer<MIN_PRICE?'La oferta mínima es $0,50.':occupied?'Ese importe ya ocupa un puesto. Elige otro valor.':''}
function renderCategoryBar(){const bar=$('categorias');bar.replaceChildren();for(const [name,icon] of categories){const b=make('button','category-button'+(name===category?' active':''));b.type='button';b.dataset.category=name;b.append(make('span','category-icon',icon),document.createTextNode(name));b.addEventListener('click',()=>{category=name;page=1;$('quick-category').value=name==='Todas'?'':name;render()});bar.append(b)}}
function projectRow(p,rank){const row=make('a','project-row'+(p.wideLogo?' wide-logo-row':''));if(p.id){row.dataset.projectId=p.id;if(p.id===targetProjectId)row.classList.add('focus-project')}row.href=validUrl(p.url)||'#';row.target='_blank';row.rel='noopener noreferrer';row.append(make('div','rank-number','#'+rank));const icon=make('div','project-icon');applyLogo(icon,p,true);icon.style.setProperty('--icon-bg',p.bg);icon.style.setProperty('--icon-fg',p.fg);row.append(icon);const info=make('div','project-info');info.append(make('span','project-title',p.name),make('div','project-description',p.description));const meta=make('div','project-meta');const strong=make('strong','',p.category);meta.append(strong,document.createTextNode(` · ${p.demo?'tu vista local':'eneltop.com'} · ${new URL(p.url).hostname} · ver detalles`));info.append(meta);row.append(info,make('div','project-bid',money(period==='today'?p.todayBid:p.bid)));return row}
const activityTitle=document.querySelector('.activity-title'),activityList=$('activity-list');
function renderProjects(){const data=filtered(),pages=Math.max(1,Math.ceil(data.length/pageSize));page=Math.min(page,pages);const start=(page-1)*pageSize;const list=$('project-list');list.replaceChildren();if(!data.length)list.append(make('div','empty-state','No hay proyectos en esta vista. Prueba otra categoría o búsqueda.'));else data.slice(start,start+pageSize).forEach((p,i)=>{list.append(projectRow(p,start+i+1));if(i===9)list.append(activityTitle,activityList)});if(!activityList.isConnected)list.append(activityTitle,activityList);$('page-count').textContent=data.length?`${start+1} – ${Math.min(start+pageSize,data.length)} de ${data.length}`:'0 proyectos';$('prev-page').disabled=page===1;$('next-page').disabled=page===pages;const nums=$('page-numbers');nums.replaceChildren();for(let i=1;i<=pages;i++){const b=make('button',i===page?'active':'',String(i));b.type='button';b.addEventListener('click',()=>{page=i;renderProjects();$('ranking').scrollIntoView({behavior:'smooth'})});nums.append(b)}}
function renderSidebar(){const today=allProjects().filter(p=>p.todayBid>0).sort((a,b)=>b.todayBid-a.todayBid||Number(Boolean(b.featured))-Number(Boolean(a.featured))).slice(0,10),list=$('today-list');list.replaceChildren();today.forEach((p,i)=>{const row=make('div','today-row');row.append(make('span','today-rank','#'+(i+1)));const icon=make('span','today-icon',p.icon);applyLogo(icon,p);icon.style.setProperty('--icon-bg',p.bg);icon.style.setProperty('--icon-fg',p.fg);const link=make('a','today-name',p.name);link.href=validUrl(p.url)||'#';link.target='_blank';link.rel='noopener noreferrer';row.append(icon,link,make('span','today-bid',money(p.todayBid)));list.append(row)});const activity=$('activity-list');activity.replaceChildren();today.slice(0,5).forEach((p,i)=>{const card=make('div','activity-card');const icon=make('span','activity-icon',p.icon);applyLogo(icon,p);icon.style.setProperty('--icon-bg',p.bg);icon.style.setProperty('--icon-fg',p.fg);const content=make('div');content.append(make('strong','',p.name.split(' · ')[0]),make('span','',`en #${i+1} · ${money(p.todayBid)}`),make('span','','en el ranking'));card.append(icon,content);activity.append(card)})}
function render(){if(automaticOffer)offer=topOffer();renderCategoryBar();renderProjects();renderSidebar();updatePrice();$('demo-count').textContent=String(allProjects().length);$('demo-revenue').textContent=money(allProjects().reduce((cents,project)=>cents+Math.round(project.bid*100),0)/100)}
for(const [name] of categories.slice(1))for(const select of [$('quick-category'),$('form-category')]){const option=make('option','',name);option.value=name;select.append(option)}
document.querySelectorAll('[data-period]').forEach(b=>b.addEventListener('click',()=>{period=b.dataset.period;page=1;document.querySelectorAll('[data-period]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',String(x===b))});render()}));
$('price-up').addEventListener('click',()=>{automaticOffer=false;const next=Number((offer+0.01).toFixed(2));if(validSavedBid(next))offer=next;updatePrice()});$('price-down').addEventListener('click',()=>{automaticOffer=false;offer=Math.max(Number((offer-0.01).toFixed(2)),MIN_PRICE);updatePrice()});for(const event of ['focus','click'])$('claim-price').addEventListener(event,e=>e.target.select());$('claim-price').addEventListener('input',e=>{const value=normalizeMoneyInput(e.target);if(value!==null){automaticOffer=false;offer=value;updatePrice(false)}});$('claim-price').addEventListener('blur',()=>updatePrice());$('prev-page').addEventListener('click',()=>{if(page>1){page--;renderProjects()}});$('next-page').addEventListener('click',()=>{if(page<Math.ceil(filtered().length/pageSize)){page++;renderProjects()}});
$('quick-category').addEventListener('change',e=>{category=e.target.value||'Todas';page=1;render()});$('quick-form').addEventListener('submit',e=>{e.preventDefault();if(!paymentsReady)return $('claim-disabled-dialog').showModal();openSubmission($('quick-url').value,$('quick-category').value||category)});
function openSubmission(url='',cat=category){const form=$('project-form'),resolved=normalizedUrl(url);form.elements.url.value=resolved||url;form.elements.category.value=isSocialProfile(resolved||url)&&(cat==='Todas'||cat==='Rankings')?'Social Media':cat==='Todas'?'Rankings':cat;writeMoneyInput(form.elements.bid,offer);updateBidNote();$('submit-dialog').showModal()}
function updateBidNote(){const cat=$('form-category').value,bid=readMoneyInput($('project-form').elements.bid);$('bid-note').textContent=validSavedBid(bid)?(allProjects().some(p=>p.bid===bid)?'Ese importe ya ocupa un puesto. Elige otro valor.':`Con ${money(bid)} quedarías en el #${rankForBid(bid,cat)} de ${cat}. Se publicará al confirmarse el pago.`):'Introduce una oferta de al menos $0,50.'}
$('form-category').addEventListener('change',updateBidNote);for(const event of ['focus','click'])$('project-form').elements.bid.addEventListener(event,e=>e.target.select());$('project-form').elements.bid.addEventListener('input',e=>{e.target.setCustomValidity('');normalizeMoneyInput(e.target);updateBidNote()});document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
$('project-logo').addEventListener('change',event=>{
  const input=event.currentTarget,file=input.files[0],preview=$('logo-preview');
  input.setCustomValidity('');preview.hidden=true;preview.replaceChildren();selectedLogo=null;logoError='';
  if(!file){logoPromise=Promise.resolve();return}
  logoPromise=(async()=>{
    if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>3_000_000)
      throw new Error('Usa JPG, PNG o WebP de hasta 3 MB.');
    const objectUrl=URL.createObjectURL(file);
    try{
      const source=new Image();
      await new Promise((resolve,reject)=>{source.onload=resolve;source.onerror=()=>reject(new Error('No se pudo abrir la imagen.'));source.src=objectUrl});
      if(source.naturalWidth<128||source.naturalHeight<128)
        throw new Error('La imagen debe medir al menos 128 × 128 px.');
      const canvas=document.createElement('canvas');canvas.width=canvas.height=192;
      const side=Math.min(source.naturalWidth,source.naturalHeight);
      const context=canvas.getContext('2d');
      if(!context)throw new Error('No se pudo preparar la imagen. Prueba otro archivo.');
      context.drawImage(source,(source.naturalWidth-side)/2,(source.naturalHeight-side)/2,side,side,0,0,192,192);
      const encoded=canvas.toDataURL('image/png');
      if(!encoded.startsWith('data:image/png;base64,')||encoded.length>400_000)
        throw new Error('No se pudo preparar la imagen. Prueba otro archivo.');
      selectedLogo=encoded;
      const img=make('img');img.src=encoded;img.alt='Vista previa del logo';
      preview.append(img,document.createTextNode('Así aparecerá en el ranking'));preview.hidden=false;
    }finally{URL.revokeObjectURL(objectUrl)}
  })().catch(error=>{logoError=error.message;input.setCustomValidity(logoError);input.reportValidity()});
});
$('project-logo').addEventListener('change',event=>{$('logo-file-name').textContent=event.currentTarget.files[0]?.name||'Ningún archivo seleccionado'});
let selectedLogo=null,logoError='',logoPromise=Promise.resolve();
$('project-form').addEventListener('submit',async e=>{e.preventDefault();if(!paymentsReady)return $('claim-disabled-dialog').showModal();const form=e.currentTarget;await logoPromise;if(logoError){$('project-logo').reportValidity();return}if(!form.reportValidity())return;const f=new FormData(form),url=validUrl(String(f.get('url'))),bid=readMoneyInput(form.elements.bid),name=String(f.get('name')).trim(),description=String(f.get('description')).trim();if(!url||!name||!description||!validSavedBid(bid)){form.elements.bid.setCustomValidity('La oferta mínima es $0,50.');form.elements.bid.reportValidity();return}if(allProjects().some(p=>p.bid===bid)){form.elements.bid.setCustomValidity('Ese importe ya ocupa un puesto. Elige otro valor.');form.elements.bid.reportValidity();return}const button=form.querySelector('[type=submit]');button.disabled=true;button.textContent='Abriendo el pago…';try{const response=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({name,description,url,category:String(f.get('category')),cents:Math.round(bid*100),logo:selectedLogo})});const data=await response.json();if(!response.ok)throw new Error(data.error||'No se pudo iniciar el pago.');window.location.assign(data.checkoutUrl)}catch(error){$('bid-note').textContent=error.message;button.disabled=false;button.textContent='Continuar al pago →'}});
$('open-search').addEventListener('click',()=>{$('search-dialog').showModal();$('search-input').focus()});$('search-input').addEventListener('input',e=>{query=e.target.value.toLowerCase().trim();page=1;renderProjects()});$('see-today').addEventListener('click',()=>{const b=document.querySelector('[data-period="today"]');b.click();$('ranking').scrollIntoView({behavior:'smooth'})});$('theme-toggle').addEventListener('click',()=>document.body.classList.toggle('dark'));
render();
async function loadRanking(){try{const response=await fetch('/api/ranking',{cache:'no-store'});if(!response.ok)throw new Error('Ranking unavailable');const data=await response.json();paidProjects=(data.projects||[]).map(p=>({...p,todayBid:new Date(p.paidAt).toISOString().slice(0,10)===new Date().toISOString().slice(0,10)?p.bid:0,icon:p.name.slice(0,1).toUpperCase(),logo:p.logo||undefined,smallLogo:p.logo||undefined,avatar:Boolean(p.profileImage&&isSocialProfile(p.url)),bg:'#e6f7f5',fg:'#267a73'}));paymentsReady=Boolean(data.paymentsEnabled);document.body.classList.toggle('payments-ready',paymentsReady);if(targetProjectId&&!targetApplied){const target=paidProjects.find(p=>p.id===targetProjectId);if(target){category=target.category;$('quick-category').value=category;period='all';const index=filtered().findIndex(p=>p.id===targetProjectId);page=Math.floor(index/pageSize)+1;targetApplied=true;render();requestAnimationFrame(()=>document.querySelector('.focus-project')?.scrollIntoView({behavior:'smooth',block:'center'}));return}}render()}catch{}}loadRanking();setInterval(loadRanking,30000);
fetch('/api/visits',{method:'POST',cache:'no-store',credentials:'same-origin'})
  .then(response=>{if(!response.ok)throw new Error('Visit counter unavailable');return response.json()})
  .then(({count})=>{if(Number.isSafeInteger(count)&&count>=0){const formatted=new Intl.NumberFormat('es-ES').format(count);$('visit-count').textContent=formatted;$('mobile-visit-count').textContent=formatted;$('header-visit-count').textContent=formatted}})
  .catch(()=>{});
