const $=id=>document.getElementById(id);
const money=value=>'$'+Number(value).toFixed(2).replace('.',',');
async function api(url,options={}){const response=await fetch(url,{credentials:'same-origin',cache:'no-store',...options});const data=await response.json();if(!response.ok)throw new Error(data.error||'No se pudo completar la solicitud.');return data}
function message(node,text,error=false){node.hidden=false;node.textContent=text;node.classList.toggle('error',error)}
function loginView(){ $('login').hidden=false;$('account').hidden=true;$('logout').hidden=true }
async function load(){try{const data=await api('/api/account');$('login').hidden=true;$('account').hidden=false;$('logout').hidden=false;$('account-email').textContent=data.email;const list=$('projects');list.replaceChildren();$('empty').hidden=data.projects.length>0;for(const project of data.projects)list.append(projectCard(project))}catch{loginView()}}
function projectCard(project){const card=document.createElement('article');card.className='card';const head=document.createElement('div');head.className='project-head';if(project.logo){const img=document.createElement('img');img.src=project.logo;img.alt='Logo actual';head.append(img)}const title=document.createElement('div');const h=document.createElement('h2');h.textContent=project.name;const sub=document.createElement('p');sub.textContent=`${project.category} · ${money(project.bid)}`;title.append(h,sub);head.append(title);card.append(head);
  const form=document.createElement('form');const label=document.createElement('label');label.textContent='URL';const url=document.createElement('input');url.type='url';url.required=true;url.value=project.url;url.maxLength=500;const photoLabel=document.createElement('label');photoLabel.textContent='Actualizar foto o logo';const photo=document.createElement('input');photo.type='file';photo.accept='image/jpeg,image/png,image/webp';const help=document.createElement('small');help.textContent='JPG, PNG o WebP · mínimo 128 × 128 px · máximo 3 MB. La imagen se recorta al centro en formato cuadrado.';const button=document.createElement('button');button.textContent='Guardar cambios';const status=document.createElement('div');status.className='message';status.hidden=true;status.setAttribute('role','status');form.append(label,url,photoLabel,photo,help,button,status);form.addEventListener('submit',async e=>{e.preventDefault();button.disabled=true;try{const logo=photo.files[0]?await prepareLogo(photo.files[0]):undefined;const body={url:url.value};if(logo)body.logo=logo;const result=await api(`/api/account/projects/${project.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(result.logo&&head.querySelector('img'))head.querySelector('img').src=result.logo;else if(result.logo){const img=document.createElement('img');img.src=result.logo;img.alt='Logo actual';head.prepend(img)}message(status,'Cambios guardados.')}catch(error){message(status,error.message,true)}finally{button.disabled=false}});
  card.append(form);const row=document.createElement('div');row.className='row';const link=document.createElement('a');link.className='button';link.href=`/p/${project.id}`;link.textContent='Ver puesto';row.append(link);card.append(row);
  const bidForm=document.createElement('form');const bidLabel=document.createElement('label');bidLabel.textContent='Nueva oferta (USD)';const amount=document.createElement('input');amount.type='number';amount.min=(Math.round(project.bid*100)+1)/100;amount.step='0.01';amount.value=((Math.round(project.bid*100)+1)/100).toFixed(2);amount.required=true;const note=document.createElement('small');note.textContent='Se cobra el importe completo de la nueva oferta. Usa el mismo correo en Dodo Payments para actualizar este puesto.';const submit=document.createElement('button');submit.textContent='Superar mi oferta →';const bidStatus=document.createElement('div');bidStatus.className='message';bidStatus.hidden=true;bidStatus.setAttribute('role','status');bidForm.append(bidLabel,amount,note,submit,bidStatus);bidForm.addEventListener('submit',async e=>{e.preventDefault();submit.disabled=true;try{const cents=Math.round(Number(amount.value)*100);const result=await api(`/api/account/bid/${project.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cents})});location.assign(result.checkoutUrl)}catch(error){message(bidStatus,error.message,true);submit.disabled=false}});card.append(bidForm);return card}
async function prepareLogo(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>3_000_000)throw new Error('Usa JPG, PNG o WebP de hasta 3 MB.');const objectUrl=URL.createObjectURL(file);try{const img=new Image();img.src=objectUrl;await img.decode();if(img.width<128||img.height<128)throw new Error('La imagen debe medir al menos 128 × 128 px.');const canvas=document.createElement('canvas');canvas.width=canvas.height=192;const size=Math.min(img.width,img.height);canvas.getContext('2d').drawImage(img,(img.width-size)/2,(img.height-size)/2,size,size,0,0,192,192);return canvas.toDataURL('image/png')}finally{URL.revokeObjectURL(objectUrl)}}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;try{await api('/api/auth/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value})});message($('login-message'),'Te enviamos un enlace de acceso. Revisa tu correo.')}catch(error){message($('login-message'),error.message,true)}finally{button.disabled=false}});
$('logout').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST'})}finally{loginView()}});
(async()=>{const token=new URLSearchParams(location.search).get('token');if(token){history.replaceState(null,'','/cuenta/');try{await api(`/api/auth/verify?token=${encodeURIComponent(token)}`,{method:'POST'})}catch(error){message($('login-message'),error.message,true)}}await load()})();
